p8105_hw2_sk5855
================
Shiyu KANG
2026-10-04

``` r
knitr::opts_chunk$set( 
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)
library(tidyverse)
```

## Question 1: NYC Subway Data

``` r
subway_df = 
  readxl::read_xlsx("NYC_Transit_Subway_Entrance_And_Exit_Data.xlsx" , na = c("","NA",".")) |>
  janitor::clean_names()

subway_df_selected = 
  subway_df |>
  select(line:entry, vending, ada) |>
  mutate(
    entry = case_match(entry, "YES" ~ 1, "NO" ~ 0)
  )
```

The dataset contains line, station name and station latitude/longitude,
which offers information on the location of stations. Route 1-10
indicates whether and what lines passed this station, 11 lines can pass
a single station at most, which is Time Square station. For data
cleaning, I first uniform the “NA” display. Then uses clean_names to
lowercase all variables and add “\_” between words. Then select
specified variables, using case_match to alter the variable type of
entry. The row of the resulting dataset is 1868, the column is 19. They
are untidy.

``` r
subway_df_selected = 
  subway_df_selected |>
     mutate(
       line_and_station_name = paste0(line,station_name)
  )

subway_df_selected |> 
  distinct(line_and_station_name) |>
  nrow() 
```

    ## [1] 465

``` r
subway_df_selected |>
  filter(ada == TRUE) |>
  distinct(line_and_station_name) |>
  nrow() 
```

    ## [1] 84

``` r
nrow(filter(subway_df_selected,vending == "NO"))/nrow(subway_df_selected)
```

    ## [1] 0.09796574

``` r
subway_df_reformat = 
  subway_df_selected |>
  pivot_longer (
    cols = route1:route11,
    names_to = "Route_number",
    names_prefix = "route",
    names_transform = list(Route_number = as.integer),
    values_to = "Route_name",
    values_transform = list(Route_name = as.character),
    values_drop_na = TRUE
  )

subway_df_reformat |>
  filter(Route_name == "A") |>
  distinct(line_and_station_name) |>
  nrow()
```

    ## [1] 60

``` r
subway_df_reformat |>
  filter(Route_name == "A", ada == TRUE) |>
  distinct(line_and_station_name) |>
  nrow()
```

    ## [1] 17

There are 60 distinct stations serving the A train, of which 17 are
ADA-compliant.

## Question 2: Trash Wheel Data

``` r
trash_df = 
  readxl::read_xlsx(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709") |>
  janitor::clean_names() |>
  mutate(
    sports_balls = as.integer(round(sports_balls))
  )

professor_df = 
  readxl::read_xlsx(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M134") |>
  janitor::clean_names() 

gwynns_df = 
  readxl::read_xlsx(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L351") |>
  janitor::clean_names() 

trash_df = trash_df |>
  mutate(
    trash_wheel = "Mr. Trash Wheel"
  )

professor_df = professor_df |>
  mutate(
    trash_wheel = "Professor Trash Wheel"
  )

gwynns_df = gwynns_df |>
  mutate(
    trash_wheel = "Gwynns Falls Trash Wheel"
  )

trash_df = trash_df |>
  mutate(year = as.integer(year))

professor_df = professor_df |>
  mutate(year = as.integer(year))

gwynns_df = gwynns_df |>
  mutate(year = as.integer(year))

combined_df = 
  bind_rows(trash_df, professor_df, gwynns_df)

total_weight = 
  combined_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarise(total_weight_tons = sum(weight_tons, na.rm = TRUE))

gwynnda_june_butts =
  combined_df |>
  filter(
    trash_wheel == "Gwynns Falls Trash Wheel",
    year == 2022,
    month == "June"
  ) |>
  summarise(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE) 
  ) |> 
      pull(total_cigarette_butts)
```

The combined dataset contains 1188 observations and 15 variables from
Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda. Each observation
represents a dumpster collection, with the `trash_wheel` variable
identifying its source. Key variables include `dumpster`, the dumpster
number; `date`, the collection date; `weight_tons`, the weight of trash
collected in tons; and `volume_cubic_yards`, its volume in cubic yards.
The dataset also records counts of specific types of litter, such as
`plastic_bottles`, `plastic_bags`, and `sports_balls`. Sports ball
counts were rounded to the nearest integer and stored as integers.
Variables unavailable for a particular trash wheel are represented by
`NA` in the combined dataset. Professor Trash Wheel collected a total of
282.26 tons of trash. Gwynnda collected 18120 cigarette butts in June
2022.

## Question 3: MCI and Amyloid Data

``` r
amyloid_df = 
  read_csv(
    file = "mci_amyloid.csv",
    skip = 1,
    na = c("",".","NA"),
    ) |>
  janitor::clean_names() 

baseline_df =
  read_csv(
    "MCI_baseline.csv",
    skip = 1,
    na = c("", ".", "NA")
  ) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      0 ~ "female",
      1 ~ "male"
    ),
    apoe4 = case_match(
      apoe4,
      0 ~ "non-carrier",
      1 ~ "carrier"
    ) 
  ) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)

baseline_summary = baseline_df |>
  summarise(
    eligible_participants = n(),
    develop_mci = sum(!is.na(age_at_onset)),
    mean_baseline_age = mean(current_age, na.rm = TRUE),
    female_carrier_proportion =
      mean(apoe4[sex == "female"] == "carrier", na.rm = TRUE)
  )
```

The baseline demographic data were imported, skipping the first row
because it contains variable descriptions rather than column names.
Blank entries, `"."`, and `"NA"` were treated as missing values, and
column names were standardized using `clean_names()`. Sex and APOE4
carrier status were recoded from numeric indicators into descriptive
categories. Participants whose MCI onset age was less than or equal to
their baseline age were excluded to ensure that all included
participants were free of MCI at baseline. Of the 483 participants
originally recruited, 479 met the inclusion criteria, and 93 developed
MCI during follow-up. Each row represents one participant, with
variables including participant ID, baseline age, sex, years of
education, APOE4 carrier status, and age at MCI onset. Among eligible
participants, the average baseline age was 65.03 years, and 30% of women
were APOE4 carriers. A missing MCI onset age indicates that the
participant remained free of MCI throughout follow-up.

``` r
amyloid_long = amyloid_df |>
  rename(id = study_id) |>
  pivot_longer(
    cols = baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_ratio"
  ) |>
  mutate(
    time = case_match(
      visit,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
    )
  ) 

#participants only appear in baseline dataset after cleaning
baseline_only =
  anti_join(
    baseline_df,
    distinct(amyloid_long, id),
    by = "id"
  )

#participants only appear in amyloid dataset after cleaning
amyloid_only =
  anti_join(
    distinct(amyloid_long, id),
    baseline_df,
    by = "id"
  )

nrow(baseline_only)
```

    ## [1] 8

``` r
nrow(amyloid_only)
```

    ## [1] 16

``` r
#participants appear in both amyloid and baseline dataset
mci_combined =
  inner_join(baseline_df, amyloid_long, by = "id")

nrow(mci_combined)
```

    ## [1] 2355

``` r
n_distinct(mci_combined$id)
```

    ## [1] 471

``` r
dir.create("data", showWarnings = FALSE)
write_csv(mci_combined, "data/mci_combined.csv")
```

The amyloid data were imported by skipping the first row of variable
descriptions, identifying missing values, and standardizing column
names. The participant identifier was renamed to `id` to match the
demographic dataset. Using `pivot_longer()`, measurements at baseline
and years 2, 4, 6, and 8 were reorganized into long format, with one row
per participant per scheduled time point. The resulting variables are
participant ID, time since baseline in years, and the amyloid 42/40
ratio. Missing biomarker values were retained as `NA`.

After applying the baseline inclusion criteria, 8 participants appeared
only in the demographic dataset, while 16 appeared only in the amyloid
dataset. These counts describe differences between the cleaned datasets;
participants excluded from the baseline dataset may still appear in the
amyloid data. An `inner_join()` by participant ID retained only
participants present in both datasets. The combined dataset contains 471
participants and 2355 participant–time-point records, with demographic
information repeated across each participant’s five scheduled visits and
missing biomarker values preserved.
